const constants = {
  CHECK_CRITERIA: "CHECK_CRITERIA",
  UNCHECK_CRITERIA: "UNCHECK_CRITERIA",
  ADD_CRITERIA: "ADD_CRITERIA",
  REMOVE_CRITERIA: "REMOVE_CRITERIA",
  COMPILE_SUGGESTIONS: "COMPILE_SUGGESTIONS"
};

export default constants;